
// This file is deprecated. All endpoints have been migrated to Supabase.
// Keeping it for reference only.

export const N8N_ENDPOINTS = {
  // LOGIN: 'DEPRECATED',
  // CHECK_PATIENT: 'DEPRECATED',
  // CREATE_PATIENT: 'DEPRECATED',
  // UPDATE_PATIENT: 'DEPRECATED',
  // DELETE_PATIENT: 'DEPRECATED',
  // URL_CALENDAR_EVENTS: 'DEPRECATED',
  // GET_AVAILABILITY: 'DEPRECATED',
  // CREATE_APPOINTMENT: 'DEPRECATED',
  // UPDATE_APPOINTMENT: 'DEPRECATED',
  // DELETE_APPOINTMENT: 'DEPRECATED'
};

export const URL_CALENDAR_EVENTS = 'DEPRECATED';
